### ISSUE TITLE
getNfts() returns testnet nfts despite changing NODE_ENV mode to production in React

### ISSUE THREAD

**Issue by artpumpkin** [Samurai-Legends/origins#15]
As the title mentioned, I can't get mainnet nfts returned by the `getNfts()` method, despite changing the `NODE_ENV` value to `production`.

This problem occurs with the vite build pack, since vite doesn't support altering environment variables directly without adding `VITE_` prefix, there are some workarounds though, unfortunately, that doesn't seem to work with this case.

One possible solution I can think of is something of this sort, which will force the mode, and let the developer handle switching and forcing modes, despite the limitations of the environment:
```TS
enum Network {
  MAINNET,
  TESTNET
}

const network: Network = Network.MAINNET;
const nfts = getNfts(network);
// => mainnet nfts
```

And if the network is not specified it can act as normal:
```ts
const nfts = getNfts();
// => mainnet/testnet nfts depending on the NODE_ENV value
```

**Comment by ThijmenMaus** [comment]
I have fixed this problem in #16.

While I do appreciate the thought of passing it as a function argument, it would be hard for me to integrate. The reason being that the object fetching happens deep inside the library, changing this would not be worth it.

I have decided to use different environment variables, see issue mentioned above for details!
