### ISSUE TITLE
Add a getNFTs method with additional prop tokenURI

### ISSUE THREAD

**Issue by artpumpkin** [Samurai-Legends/origins#6]
Upon developing the _marketplace API_, we had to develop another API called _marketplace-metadata_ that was depending on a **CSV** file to get mainnet/testnet contract, tokenURI for every NFT, the tokenURI was used as the source of truth to construct the filter metadata which will be used by the _marketplace API_ later.

This issue is trying to solve 2 problems:
1. Getting all SamuraiLegends NFTs at once
2. Getting additional properties for every NFT like tokenURI, type

**Interface**
```ts
enum NFTType {
  UNITS,
  LANDS,
  PETS,
  EQUIPMENTS,
  IMPERIAL_DROPS
}

interface NFT {
  name: string;
  contractAddress: string;
  tokenURI: string;
  type: NFTType;
}
```

**Sample**
```ts
import { getNFTs } from "@samurailegends/origins";

const nfts = getNFTs();
// => Array<NFT>
```

**Comment by ThijmenMaus** [comment]
This will need a proper restructure, will release as a a new minor `x.1.x` version.

**Comment by ThijmenMaus** [comment]
#11
